### ISSUE TITLE
sendCommand and exec with diferent Prompts doesnt Work!?

### ISSUE THREAD

**Issue by xmaxmex** [diotteo/TelnetClient.php#1]
The Server have 3 steps for this command:

Login Prompt is OK!

1 cmd
epon>enable

2 cmd
epon#configure terminal

3 cmd
epon(config)#show onu-status

Gives alway timed out!

Sample code:

$prompt = "epon>";

$telnet = new TelnetClient($OLT_REMOTE_IP, $OLT_TCP_PORT);
$telnet->connect();
$telnet->setPrompt($prompt); //setRegexPrompt() to use a regex

$telnet->setPruneCtrlSeq(true); //Enable this to filter out ANSI control/escape sequences

	$telnet->login($username, $password, $loginPrompt, $passPrompt);

	$telnet->sendCommand('enable');	
	sleep(1);	
	$telnet->sendCommand('configure terminal');	
	sleep(1);	
	$telnet->sendCommand('show onu-status');

		do {
			$line = $telnet->getLine($matchesPrompt);
			//print($line).'@<br>';
			$linha .= $line;			
		} while (!$matchesPrompt);

Stops with timed out. Any help ?

**Comment by diotteo** [comment]
You need to ->sendCommand() and then ->waitPrompt() (or do something other with the output returned, as appropriate), not sleep().

If you just want to send a command, wait for a prompt, send another command, use the ->exec() method. It also returns the output, see the phpdoc.

**Comment by diotteo** [comment]
To be clear, this is what your code would look like:

```php
$telnet = new TelnetClient($OLT_REMOTE_IP, $OLT_TCP_PORT);
$telnet->connect();
$telnet->setPrompt($prompt); //setRegexPrompt() to use a regex

$telnet->setPruneCtrlSeq(true); //Enable this to filter out ANSI control/escape sequences

$telnet->login($username, $password, $loginPrompt, $passPrompt);

$telnet->exec('enable');	
$telnet->exec('configure terminal');	
$status_str = $telnet->exec('show onu-status');
print("Status is: " . $status_str)
```

**Comment by xmaxmex** [comment]
Hi, thansk for the feedback!

Using this example. The code returns timed out.

`<?php
include "config.php";

require_once(__DIR__ . '/TelnetClient/TelnetClient.php');

use TelnetClient\TelnetClient;

TelnetClient::setDebug(true);

$loginPrompt = 'Username(1-32 chars):';
$passPrompt = 'Password(1-16 chars):';
$prompt = 'OLT4840E>';

$username = "admin";
$password = "admin";

$telnet = new TelnetClient($OLT_REMOTE_IP, $OLT_TCP_PORT);
$telnet->connect();
$telnet->setPrompt($prompt); //setRegexPrompt() to use a regex

$telnet->setPruneCtrlSeq(true); //Enable this to filter out ANSI control/escape sequences

$telnet->login($username, $password, $loginPrompt, $passPrompt);

$telnet->exec('enable');	
$telnet->exec('configure terminal');	
$status_str = $telnet->exec('show onu-status');
print("Status is: " . $status_str)

?>`

Fatal error: Uncaught exception 'TelnetClient\ConnectionTimeoutException' with message 'Timed out' in C:\itec-inet\Apache24\htdocs\oltshow\TelnetClient\TelnetClient.php:718 Stack trace: #0 C:\itec-inet\Apache24\htdocs\oltshow\TelnetClient\TelnetClient.php(673): TelnetClient\TelnetClient->getMoreData(Array) #1 C:\itec-inet\Apache24\htdocs\oltshow\TelnetClient\TelnetClient.php(967): TelnetClient\TelnetClient->getNextLine() #2 C:\itec-inet\Apache24\htdocs\oltshow\TelnetClient\TelnetClient.php(452): TelnetClient\TelnetClient->waitPrompt(true) #3 C:\itec-inet\Apache24\htdocs\oltshow\epon2.php(24): TelnetClient\TelnetClient->exec('enable') #4 {main} thrown in C:\itec-inet\Apache24\htdocs\oltshow\TelnetClient\TelnetClient.php on line 718

With debug true, return this:

Waiting for prompt "Username\(1\-32 chars\)\:" [CMD WILL][OPT Echo] Adding (0x1b) to buffer Adding "[" to buffer Adding "2" to buffer Adding "J" to buffer Adding (0x1b) to buffer Adding "[" to buffer Adding "1" to buffer Adding ";" to buffer Adding "1" to buffer Adding "H" to buffer Adding (0x0a) to buffer Adding "U" to buffer Adding "s" to buffer Adding "e" to buffer Adding "r" to buffer Adding "n" to buffer Adding "a" to buffer Adding "m" to buffer Adding "e" to buffer Adding "(" to buffer Adding "1" to buffer Adding "-" to buffer Adding "3" to buffer Adding "2" to buffer Adding " " to buffer Adding "c" to buffer Adding "h" to buffer Adding "a" to buffer Adding "r" to buffer Adding "s" to buffer Adding ")" to buffer Adding ":" to buffer Waiting for prompt "Password\(1\-16 chars\)\:" Adding "a" to buffer Adding "d" to buffer Adding "m" to buffer Adding "i" to buffer Adding "n" to buffer Adding (0x0a) to buffer Adding "P" to buffer Adding "a" to buffer Adding "s" to buffer Adding "s" to buffer Adding "w" to buffer Adding "o" to buffer Adding "r" to buffer Adding "d" to buffer Adding "(" to buffer Adding "1" to buffer Adding "-" to buffer Adding "1" to buffer Adding "6" to buffer Adding " " to buffer Adding "c" to buffer Adding "h" to buffer Adding "a" to buffer Adding "r" to buffer Adding "s" to buffer Adding ")" to buffer Adding ":" to buffer Waiting for prompt "OLT4840E\>" Adding "*" to buffer Adding "*" to buffer Adding "*" to buffer Adding "*" to buffer Adding "*" to buffer Adding (0x1b) to buffer Adding "[" to buffer Adding "2" to buffer Adding "J" to buffer Adding (0x1b) to buffer Adding "[" to buffer Adding "1" to buffer Adding ";" to buffer Adding "1" to buffer Adding "H" to buffer Adding (0x0a) to buffer Adding "O" to buffer Adding "L" to buffer Adding "T" to buffer Adding "4" to buffer Adding "8" to buffer Adding "4" to buffer Adding "0" to buffer Adding "E" to buffer Adding ">" to buffer Waiting for prompt "OLT4840E\>" Adding "e" to buffer Adding "n" to buffer Adding "a" to buffer Adding "b" to buffer Adding "l" to buffer Adding "e" to buffer Adding (0x0a) to buffer Adding "O" to buffer Adding "L" to buffer Adding "T" to buffer Adding "4" to buffer Adding "8" to buffer Adding "4" to buffer Adding "0" to buffer Adding "E" to buffer Adding "#" to buffer
Fatal error: Uncaught exception 'TelnetClient\ConnectionTimeoutException' with message 'Timed out' in C:\itec-inet\Apache24\htdocs\oltshow\TelnetClient\TelnetClient.php:718 Stack trace: #0 C:\itec-inet\Apache24\htdocs\oltshow\TelnetClient\TelnetClient.php(673): TelnetClient\TelnetClient->getMoreData(Array) #1 C:\itec-inet\Apache24\htdocs\oltshow\TelnetClient\TelnetClient.php(967): TelnetClient\TelnetClient->getNextLine() #2 C:\itec-inet\Apache24\htdocs\oltshow\TelnetClient\TelnetClient.php(452): TelnetClient\TelnetClient->waitPrompt(true) #3 C:\itec-inet\Apache24\htdocs\oltshow\epon2.php(25): TelnetClient\TelnetClient->exec('enable') #4 {main} thrown in C:\itec-inet\Apache24\htdocs\oltshow\TelnetClient\TelnetClient.php on line 718


Awaiting...

**Comment by diotteo** [comment]
```
Waiting for prompt "OLT4840E>"
Adding "e" to buffer
Adding "n" to buffer
Adding "a" to buffer
Adding "b" to buffer
Adding "l" to buffer
Adding "e" to buffer
Adding (0x0a) to buffer
Adding "O" to buffer
Adding "L" to buffer
Adding "T" to buffer
Adding "4" to buffer
Adding "8" to buffer
Adding "4" to buffer
Adding "0" to buffer
Adding "E" to buffer
Adding "#" to buffer
```

You're waiting for `OLT4840E>` but it's returning `OLT4840E#`. The code works, it obviously worked for your login and password. The rest is debugging you need to do using your device. Try just logging in and waiting for the prompt, see if that works without timing out for example.

Anyway, closing this since it's not an issue in the library itself.

**Comment by xmaxmex** [comment]
Agree.


Em dom, 29 de mar de 2020 22:32, Olivier Diotte <notifications@github.com>
escreveu:
